NDefines.NNavy.DETECTION_SUBS_CHANCE_BALANCE = 85.0 --Higher means less chance of detection
NDefines.NNavy.COMBAT_TORPEDO_ATTACK_MAX_RANGE = 4.5
NDefines.NNavy.COMBAT_TORPEDO_ATTACK_USE_CHANCE = 0.45
NDefines.NNavy.COMBAT_EVASION_TO_HIT_CHANCE_TORPEDO_MULT = 60.0
NDefines.NNavy.SUBMARINE_REVEAL_BASE_CHANCE = 0.002
NDefines.NNavy.SUBMARINE_HIDE_TIMEOUT = 4
NDefines.NNavy.SUBMARINE_REVEALED_TIMEOUT = 8
